export const GOAL_RECOMMENDATIONS: string[] = [
  'Drink 8 glasses of water today',
  'Take a 10-minute walk outside',
  'Call or text a friend',
  'Make my bed',
  'Eat a healthy breakfast',
  'Practice deep breathing for 5 minutes',
  "Write down 3 things I'm grateful for",
  'Take my medications on time',
  'Shower and get dressed',
  'Do 10 minutes of stretching',
  'Read for 15 minutes',
  'Listen to my favorite music',
  'Prepare a healthy lunch',
  'Organize one small area of my space',
  'Spend 10 minutes in the sun',
  'Do a small chore (dishes, laundry, etc.)',
  'Practice a hobby I enjoy',
  'Limit social media to 30 minutes',
  'Go to bed by 10 PM',
  'Journal about my day',
  'Meditate for 10 minutes',
  'Reach out to my therapist/counselor',
  'Cook a meal from scratch',
  'Take a relaxing bath',
  'Do one thing that makes me smile',
  'Pet or spend time with an animal',
  'Watch a favorite show or movie',
  'Complete one work/school task',
  'Practice saying no to something',
  'Take a break when I need it',
  'Eat three meals today',
  'Open my windows for fresh air',
  'Water my plants',
  'Do a 5-minute cleanup',
  'Take progress photos or notes',
  'Attend a support group or meeting',
  'Try a new healthy recipe',
  'Do a random act of kindness',
  'Declutter one drawer or surface',
  "Schedule an appointment I've been avoiding",
  'Practice positive self-talk',
  'Avoid negative triggers today',
  'Spend time on a creative project',
  'Exercise for 20 minutes',
  'Practice mindfulness while eating',
  'Connect with nature somehow',
  'Do a guided relaxation exercise',
  'Celebrate a small win',
  'Ask for help when I need it',
  'Be gentle with myself today',
];
