name: Deploy to Dev

on:
  push:
    branches:
      - develop
    paths:
      - '**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-app-deploy:
    uses: ./.github/workflows/app.yml
    with:
      environment_name: dev
